### ISSUE TITLE
Memory and CPU issues

### ISSUE THREAD

**Issue by Jackster35** [vram4/Ogar#104]
Hey vram4, first I'd like to say you're doing an awesome job on this fork on Ogar.
But there's a slight issue, I run 3 game servers on one machine with 4GB of RAM and a Xeon dedicated 4 cores.
When they all boot up it's fine, and when each has around 60 players it's also fine but after a little while of holding 60 or so players, it'll eventually start to memory leak or CPU leak causing massive amounts of lag. Here are images of the memory leak: 

(P.S, the first two servers have 5 bots each)

http://i.imgur.com/JreLNkN.png
http://i.imgur.com/UAtPzJ6.png

Thank you bro :)

**Comment by Eureka22** [comment]
You can see #85 for more details

**Comment by Jackster35** [comment]
Thank you. :+1:

**Comment by vram4** [comment]
Are you using the latest commit? I pushed a potential fix for the memory issue.

**Comment by Jackster35** [comment]
Hey yeah I literally just updated it, thank you! I'll let you know how it plays out bro :)

**Comment by Jackster35** [comment]
Update: The memory issue is still present, although it takes a lot longer to max out the server's ram. I guess it's a fix but only for a short time. :)

**Comment by Eureka22** [comment]
@Jackster35 same problem :+1:
